-- =============================================================================
-- base_conhecimento_seed.sql
--
-- P26 (PROMPTS.md) · PRD 3, 11 e 19.2
--
-- Rascunho inicial da base de conhecimento do agente (agente.base_conhecimento),
-- para o Leonardo e a Edilaine aprovarem pela tela do P27 antes de qualquer
-- item virar indexável pelo fluxo 1 (19.2: só item com status = 'aprovado'
-- entra no PGVector). Todo item aqui entra em 'rascunho', de propósito.
--
-- Fontes: PRD.md capítulos 3 e 11; n8n/prompts/isadora-system.md, seção "O
-- que a Kraamzorg é"; e a Apresentação Institucional 2026 (Drive, páginas
-- citadas por item na coluna fonte). Nada clínico (protocolos, sinais de
-- alerta, condutas): a Isadora não orienta clinicamente (PRD 19.2).
-- Depoimentos não entram, porque dependem de autorização de uso do nome (PRD
-- 19.2, 11.5). As vinte conversas reais do treinamento de 24/09 também não
-- entram aqui nem em nenhum outro lugar do repositório (PRD 11.5, CLAUDE.md).
--
-- Um assunto por item (enum tipo_conteudo), texto até 1500 caracteres (check
-- da tabela) e fonte sempre preenchida. 29 itens: institucional (7, incluindo
-- os contatos oficiais), equipe (1), faq (10, incluindo "para quem é" e
-- "reserva"), cobertura (1), política (1) e objeção (9, as objeções do
-- prompt de produção da Isadora, n8n/prompts/isadora-system.md).
--
-- Nenhum valor em reais aparece nos textos, de propósito: preço muda e o
-- vetor não seria atualizado sozinho (mesmo cuidado que o 19.2 pede para os
-- documentos de plano do nó 5, "sem valor, porque o valor vem da ficha a
-- cada mensagem e envelhece no vetor"). Quem cita valor à família é sempre a
-- ficha da conversa, nunca a base de conhecimento.
-- =============================================================================

insert into agente.base_conhecimento (tipo, titulo, texto, fonte, status) values
  ('institucional', 'O que é a Kraamzorg Brasil', 'Kraamzorg é uma palavra holandesa para o cuidado domiciliar profissional da mãe e do recém-nascido nos primeiros dias depois do parto. Na Holanda esse cuidado é padrão nacional desde 1900. A Kraamzorg Brasil nasceu inspirada nesse modelo e adaptada às famílias brasileiras, com sedes em São Paulo e em Londrina.

A Kraamzorg oferece um cuidado continuado, organizado com método, presença e coordenação, pensado para o período mais delicado da maternidade, os primeiros dias em casa. Esse formato ocupa um espaço próprio, diferente do que uma doula, um cuidador avulso, um home care genérico ou uma consultoria isolada costumam entregar. A Kraamzorg complementa o médico da família e fica entre a alta hospitalar e a rotina que ainda está nascendo.', 'Apresentação Institucional 2026 p.1 a 4', 'rascunho'),
  ('institucional', 'Por que os primeiros dias em casa importam', 'Os primeiros dias depois do parto costumam ser os mais delicados e os menos amparados. O corpo da mãe ainda se reorganiza, o bebê chega com necessidades constantes e a rotina da casa ainda está se formando, muitas vezes sem ninguém por perto com preparo técnico para ajudar.

Segundo o Ministério da Saúde, 75% das complicações neonatais acontecem na primeira semana de vida, justamente quando a família já voltou para casa e o acompanhamento hospitalar terminou. É por isso que a Kraamzorg concentra o cuidado exatamente nessa janela: presença diária, orientação clara e alguém preparado por perto enquanto tudo ainda está novo.', 'Apresentação Institucional 2026 p.2 (Ministério da Saúde/BR)', 'rascunho'),
  ('institucional', 'Como funciona o cuidado, passo a passo', 'O cuidado da Kraamzorg acontece em quatro momentos. Primeiro, o pré-natal online, antes do parto: um encontro com a família para conversar, alinhar expectativas e montar o plano de cuidado. Faz parte de todos os pacotes.

Depois vem a alta hospitalar, o gatilho real do início: a família volta para casa e o cuidado continua a partir dali. No terceiro momento, uma enfermeira obstétrica ou neonatal visita a família todos os dias, do dia 1 ao dia 6 ou ao dia 12 conforme o pacote, sempre no mesmo período do dia, manhã ou tarde, inclusive fim de semana e feriado. É a mesma enfermeira do primeiro ao último dia.

No fim, o resultado que a Kraamzorg busca: família mais segura, mãe mais tranquila, bebê acompanhado de perto, parceiro mais preparado e uma rotina que já está de pé.', 'Apresentação Institucional 2026 p.5', 'rascunho'),
  ('institucional', 'As quatro frentes de cada visita', 'Cada visita da enfermeira cuida de quatro frentes ao mesmo tempo, com uma coordenação só, para a família não ouvir orientações repetidas ou conflitantes de pessoas diferentes.

A mãe: presença atenta à recuperação física e ao bem-estar emocional, com espaço para tirar as dúvidas do dia a dia. O bebê: acompanhamento próximo da rotina, do sono, da alimentação e dos cuidados diários. A amamentação: apoio técnico e humano, todos os dias, sem imposição. A família: orientação ao parceiro e a quem estiver ajudando, para que ninguém aprenda essa fase sozinho e a rotina da casa se organize com menos conflito.

Essa visão geral não substitui a avaliação da enfermeira em cada visita, que segue protocolo próprio da coordenação de enfermagem.', 'Apresentação Institucional 2026 p.6; n8n/prompts/isadora-system.md', 'rascunho'),
  ('institucional', 'Amamentação: como a Kraamzorg apoia', 'O apoio à amamentação acontece em todas as visitas, com acompanhamento diário da pega e da posição, ajustes práticos de conforto para a mãe e o bebê, e laserterapia para dor e cicatrização do mamilo quando indicada. O acompanhamento é respeitoso e sem imposição: cada amamentação tem sua história, e o papel da equipe é amparar essa história, não corrigi-la de cima para baixo.

Uma revisão sistemática publicada pela BVSalud documenta aumento de 12% para 67% no aleitamento materno exclusivo quando a família recebe visitas domiciliares de suporte qualificado nos primeiros dias. É um dado sobre o que a presença estruturada costuma favorecer, não uma promessa de resultado individual: cada mãe e cada bebê seguem seu próprio ritmo.', 'Apresentação Institucional 2026 p.7 (BVSalud); n8n/prompts/isadora-system.md', 'rascunho'),
  ('institucional', 'Evidências científicas por trás do protocolo', 'O protocolo de visitas da Kraamzorg segue pesquisa publicada por instituições nacionais e internacionais, entre elas o NIH, a PMC, o Ministério da Saúde e a BVSalud. As áreas estudadas incluem recuperação física mais segura para a mãe, redução da ansiedade e da insegurança materna no puerpério, detecção precoce de complicações neonatais, menos idas desnecessárias ao pronto-socorro e melhora do aleitamento materno exclusivo.

Use essas evidências para explicar por que o cuidado existe nesse formato, nunca como promessa de resultado para uma família específica: o que a pesquisa mostra é uma tendência de grupo, e cada família vive a sua própria experiência.', 'Apresentação Institucional 2026 p.8 (NIH, PMC, MS Brasil, BVSalud)', 'rascunho'),
  ('equipe', 'Quem atende: fundadores e equipe técnica', 'A Kraamzorg Brasil foi fundada por Leonardo Giovanini Rossetto, médico ginecologista e obstetra com pós-graduação em Medicina Fetal, que viu na prática clínica a falta de cuidado entre o hospital e a casa da paciente, e por Edilaine Giovanini Rossetto, enfermeira, mestre e doutora em Enfermagem em Saúde Pública pela USP, com mais de 20 anos em saúde materno-infantil e coordenadora de um projeto multicêntrico financiado pela Fundação Bill & Melinda Gates. Os dois são mãe e filho, com formações que se completam.

Os atendimentos domiciliares são feitos por enfermeiras obstétricas ou neonatais especializadas, alinhadas a protocolo internacional e integradas ao cuidado médico da família. A equipe atua em São Paulo e Londrina, sob coordenação de enfermagem da Edilaine. A Kraamzorg não substitui o médico da família: complementa, como a ponte entre o hospital e a vida real em casa.', 'Apresentação Institucional 2026 p.9 e 10; PRD 3', 'rascunho'),
  ('faq', 'Para quem é o cuidado da Kraamzorg', 'É para toda família que quer atravessar os primeiros dias em casa com mais presença e segurança, em qualquer situação: primeiro filho ou segundo bebê, parto normal ou cesárea, gestação única ou gêmeos, com rede de apoio por perto ou mãe solo. O cuidado também pode ser dado de presente: o contrato fica no nome de quem recebe o cuidado, o pagamento fica com quem presenteia, e a equipe prepara um cartão especial para a ocasião.

O que muda entre as famílias é o formato escolhido, nunca a atenção recebida: o método e as quatro frentes de cuidado são os mesmos para todo mundo.', 'Apresentação Institucional 2026 p.13; PRD 11.8', 'rascunho'),
  ('faq', 'Como funciona a reserva', 'A reserva é feita antes do parto, pela data provável do parto, a DPP. A janela ideal para reservar fica entre 28 e 36 semanas de gestação, e a contratação abre a partir de 20 semanas. Se o bebê chegar antes ou depois da DPP, a equipe organiza a agenda a partir da reserva já feita e acompanha a família nesse ajuste.

A Kraamzorg atende um número limitado de famílias por semana em cada região, até 3, para manter presença total e o mesmo padrão técnico em cada visita. Depois da reserva confirmada, o pré-natal online é agendado e a enfermeira responsável pelo acompanhamento é designada.', 'Apresentação Institucional 2026 p.15; PRD 3.6', 'rascunho'),
  ('faq', 'Como funciona o cuidado, resumido', 'O cuidado começa com um pré-natal online, antes do parto, para conhecer a família e montar o plano. Depois da alta hospitalar, uma enfermeira obstétrica ou neonatal visita a família todos os dias, sempre no mesmo período, do dia 1 ao dia 6 ou ao dia 12 conforme o pacote escolhido, cuidando da mãe, do bebê, da amamentação e da família numa coordenação só. É a mesma enfermeira do início ao fim do acompanhamento.', 'Apresentação Institucional 2026 p.5; n8n/prompts/isadora-system.md', 'rascunho'),
  ('cobertura', 'Atendem a minha região?', 'A Kraamzorg atende famílias em São Paulo capital e região, incluindo Alphaville, e em Londrina e região, incluindo Apucarana e Arapongas. Algumas cidades fora da capital têm taxa de deslocamento, que a equipe confirma com a família caso a caso. Fora dessas praças, ainda não há atendimento, embora a Kraamzorg esteja de olho em outras regiões para o futuro.

A confirmação da cobertura para o endereço exato da família sempre passa pela equipe, nunca pelo DDD do telefone.', 'PRD 3.3', 'rascunho'),
  ('faq', '6 dias ou 12 dias: qual a diferença?', 'Os formatos Essencial e Imersão duram 6 dias consecutivos, com visitas de 3 e 6 horas por dia. O Continuado dura 12 dias consecutivos, com visitas de 3 horas por dia. Para gestação de gêmeos, os formatos gemelares seguem a mesma lógica, com visitas de 4 horas por dia, porque são duas rotinas ao mesmo tempo.

Em qualquer formato, é a mesma enfermeira do primeiro ao último dia, sempre no mesmo período do dia, manhã ou tarde. O cuidado é o mesmo em todos os formatos: o que muda é o número de dias e a duração de cada visita.', 'PRD 3.2; Apresentação Institucional 2026 p.5, 11 e 12', 'rascunho'),
  ('faq', 'A Kraamzorg substitui a doula?', 'Não. A Kraamzorg tem um papel diferente do de uma doula, de um cuidador avulso, de um home care genérico ou de uma consultoria isolada. Uma família que já conta com doula ou outro profissional de apoio pode somar o cuidado da Kraamzorg a esse acompanhamento: a visita diária de uma enfermeira especializada olha para a mãe, o bebê, a amamentação e a família juntos, com método e coordenação de enfermagem, o que nenhum desses outros formatos entrega sozinho.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('faq', 'Quando o cuidado começa?', 'O cuidado em casa começa na alta hospitalar, o gatilho real do início: assim que a família volta para casa, a enfermeira passa a visitar todos os dias, do dia 1 ao dia 6 ou ao dia 12 conforme o pacote. Antes disso, ainda durante a gestação, acontece o pré-natal online, incluído em todos os pacotes, para preparar a família com antecedência.', 'Apresentação Institucional 2026 p.5; PRD 3.6', 'rascunho'),
  ('faq', 'E se o bebê nascer antes ou depois da data prevista?', 'A reserva é feita pela data provável do parto, a DPP, e a equipe organiza a agenda a partir dela. Se o bebê chegar antes ou depois da data prevista, a equipe acompanha a família e ajusta o início do atendimento conforme a nova data, sem que a família precise refazer a reserva do zero.', 'n8n/prompts/isadora-system.md, seção Situações especiais; PRD 3.6', 'rascunho'),
  ('faq', 'O cuidado é feito de dia ou também à noite?', 'O cuidado da Kraamzorg acontece de dia, num período fixo combinado na reserva, manhã ou tarde. Não há atendimento noturno, pernoite, plantão nem diária avulsa: a enfermeira visita, cuida e orienta a família para o resto do dia e para a noite, mas não permanece na casa fora do horário da visita.', 'PRD 3.1 e 3.2; n8n/prompts/isadora-system.md', 'rascunho'),
  ('faq', 'Posso parcelar o pagamento?', 'Sim. Todos os pacotes podem ser pagos à vista ou parcelados em até 3 vezes sem juros no cartão. Pode haver taxa de deslocamento conforme a localização da família, e qualquer condição diferente da tabela, como mais parcelas ou desconto, é combinada diretamente com o Leonardo.', 'PRD 3.2; Apresentação Institucional 2026 p.11 e 12', 'rascunho'),
  ('faq', 'Vocês emitem nota fiscal?', 'Sim, a Kraamzorg emite nota fiscal, e ela descreve o serviço como cuidado domiciliar pós-parto. O reembolso do valor pago depende das regras do plano de saúde ou do convênio de cada família, então vale a pena a família consultar diretamente com eles antes de contar com o reembolso.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('politica', 'O que a Kraamzorg não oferece', 'A Kraamzorg não tem atendimento noturno, pernoite, plantão, diária avulsa nem atendimento dentro do hospital, e não existe serviço avulso fora dos pacotes. Extensão do acompanhamento é possível conforme a disponibilidade da enfermeira, e quem trata dessa condição é o Leonardo.

A Kraamzorg também não substitui o obstetra, o pediatra nem o pronto atendimento da família: o cuidado é complementar, entre o hospital e a vida real em casa, sempre em conexão com o médico que já acompanha a família.', 'PRD 3.2 e 11.2; n8n/prompts/isadora-system.md', 'rascunho'),
  ('objecao', 'Objeção: "está caro"', 'O investimento costuma ser o primeiro ponto que a família quer entender com calma, e isso faz todo sentido diante de uma decisão importante. Vale explicar a diferença entre os formatos, para a família achar o que combina com a rotina e o orçamento dela, e oferecer a conversa com a Edilaine para tirar dúvidas sem compromisso. Nunca minimize a preocupação com frases como "saúde não tem preço", e nunca demonstre estar na defensiva.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "vou decidir com meu parceiro"', 'Decidir junto faz todo sentido para uma escolha desse tamanho. Os dois podem participar juntos da conversa com a Edilaine, para tirar as dúvidas ao mesmo tempo e chegar à decisão com mais segurança.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "minha família vai me ajudar, não preciso"', 'Ter família por perto é uma sorte real, e a Kraamzorg não substitui esse apoio: soma a ele. A enfermeira cuida da parte técnica da mãe e do bebê, com protocolo e olhar treinado, e ainda orienta quem estiver ajudando na rotina da casa, para que todo mundo, inclusive a família que está ajudando, fique mais seguro sobre o que fazer.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "já tenho doula ou outro profissional de apoio"', 'Que bom que a família já está se cuidando. A Kraamzorg pode somar a esse acompanhamento, não competir com ele: é uma visita diária de uma enfermeira especializada, olhando a mãe, o bebê, a amamentação e a família ao mesmo tempo, com método e coordenação de enfermagem. Nunca compare ou critique outro profissional de apoio ao decidir com a família.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "são só algumas horas por dia, é suficiente?"', 'A visita diária cuida da mãe e do bebê de perto e deixa a família orientada para o restante do dia, com uma rotina mais clara em vez de tentativa e erro. Existem formatos com durações diferentes, de 3 a 6 horas por dia, para a família escolher o que combina melhor com o momento dela. Nenhum número de horas serve igual para todo mundo, então vale entender o contexto da família antes de indicar um formato.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "quero atendimento durante a noite"', 'O cuidado da Kraamzorg acontece durante o dia, com enfermeiras especializadas, e não inclui acompanhamento noturno. Durante as visitas, a enfermeira orienta a família para se organizar melhor também durante as noites. Não critique quem procura cuidado noturno e não indique outro serviço por conta própria.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "é gratuito, como na Holanda?"', 'Na Holanda, esse cuidado faz parte do sistema público de saúde. No Brasil, o atendimento da Kraamzorg é particular, com pacotes e valores detalhados na apresentação oficial. O modelo é o mesmo em espírito, presença estruturada nos primeiros dias, mas o formato de acesso muda de um país para o outro.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "qual enfermeira vai atender a gente?"', 'Todas as enfermeiras da equipe são especializadas, obstétricas ou neonatais, e seguem o mesmo protocolo de atendimento. A profissional responsável é definida no momento da reserva e acompanha a família do primeiro ao último dia. Os nomes da equipe não são informados durante a conversa comercial.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('objecao', 'Objeção: "o contrato vai ter tudo o que está na apresentação?"', 'O que está na apresentação oficial é o que a Kraamzorg entrega, e faz todo sentido a família querer essa clareza antes de assinar. Os detalhes contratuais, como cláusulas, prazos e condições de pagamento, são tratados diretamente pelo Leonardo no momento da contratação.', 'n8n/prompts/isadora-system.md, seção Objeções', 'rascunho'),
  ('institucional', 'Contatos oficiais da Kraamzorg', 'O atendimento comercial de famílias interessadas no cuidado acontece pelo WhatsApp, com a Isadora ou com a equipe. Para assuntos que não são o cuidado de uma família, como candidaturas, fornecedores e parcerias, o contato oficial é contato@kraamzorgbrasil.com.br.

Outros canais oficiais da marca: o site kraamzorgbrasil.com.br e o perfil @kraamzorgbrasil nas redes sociais. Esses canais servem para informação institucional; o atendimento de uma família específica sempre acontece pela conversa já em andamento, nunca repetindo o processo em outro canal.', 'Apresentação Institucional 2026 p.16; n8n/prompts/isadora-system.md', 'rascunho');
